# goods-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: goods-svc
  namespace: my-springcloud
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: goods
---
# goods-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goods
  namespace: my-springcloud
  labels:
    app: goods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goods
  template:
    metadata:
      labels:
        app: goods
    spec:
      imagePullSecrets:
        - name: harbor-cred
      containers:
        - name: goods
          image: 192.168.10.16:9090/gmall/goods:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR
              value: "nacos-svc.my-springcloud:8848"
            - name: SPRING_CLOUD_NACOS_CONFIG_SERVERADDR
              value: "nacos-svc.my-springcloud:8848"
            - name: SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE
              value: "494ba071-c625-44c7-94c9-5a4ee408f573"
            - name: SPRING_CLOUD_NACOS_CONFIG_NAMESPACE
              value: "494ba071-c625-44c7-94c9-5a4ee408f573"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
