# review-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: review-svc
  namespace: my-springcloud
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
  selector:
    app: review
---
# review-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review
  namespace: my-springcloud
  labels:
    app: review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      imagePullSecrets:
        - name: harbor-cred
      containers:
        - name: review
          image: 192.168.10.16:9090/gmall/review:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR
              value: "nacos-svc.my-springcloud:8848"
            - name: SPRING_CLOUD_NACOS_CONFIG_SERVERADDR
              value: "nacos-svc.my-springcloud:8848"
            - name: SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE
              value: "494ba071-c625-44c7-94c9-5a4ee408f573"
            - name: SPRING_CLOUD_NACOS_CONFIG_NAMESPACE
              value: "494ba071-c625-44c7-94c9-5a4ee408f573"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
