# user-center-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-center-svc
  namespace: my-springcloud
spec:
  type: ClusterIP
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: user-center
---
# user-center-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-center
  namespace: my-springcloud
  labels:
    app: user-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-center
  template:
    metadata:
      labels:
        app: user-center
    spec:
      imagePullSecrets:
        - name: harbor-cred
      containers:
        - name: user-center
          image: 192.168.10.16:9090/gmall/user-center:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR
              value: "nacos-svc.my-springcloud:8848"
            - name: SPRING_CLOUD_NACOS_CONFIG_SERVERADDR
              value: "nacos-svc.my-springcloud:8848"
            - name: SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE
              value: "494ba071-c625-44c7-94c9-5a4ee408f573"
            - name: SPRING_CLOUD_NACOS_CONFIG_NAMESPACE
              value: "494ba071-c625-44c7-94c9-5a4ee408f573"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
